apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      run: webserver
  template:
    metadata:
      annotations:
#        secret.k8s.aws/sidecarInjectorWebhook: enabled
#        secret.k8s.aws/secret-arn: ${SECRET_ARN}
        secrets.k8s.aws/sidecarInjectorWebhook: enabled
        secrets.k8s.aws/secret-arn: ${SECRET_ARN}
      labels:
        run: webserver
    spec:
      serviceAccountName: default
      volumes:
        - name: secret-vol
          emptyDir:
            medium: Memory
      containers:
      - image: busybox:1.28
        name: webserver
        command: ['sh', '-c', 'echo $(cat /tmp/secret) && sleep 3600']
        volumeMounts:
          - name: secret-vol
            mountPath: /tmp
      initContainers:
      - name: aws-secrets-manager
        image: amazon/aws-secrets-manager-secret-sidecar:v0.1.1
        env:
          - name: SECRET_ARN
            valueFrom:
              fieldRef: 
#                fieldPath: metadata.annotations['secret.k8s.aws/secret-arn']
                fieldPath: metadata.annotations['secrets.k8s.aws/secret-arn']
        volumeMounts:
          - name: secret-vol
            mountPath: /tmp
